name: "Unit tests"
on: 
  pull_request_target: 
    branches:
      - master
  push: 
    branches: 
      - master
  
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v3.8.1
        with:
          node-version: ${{ matrix.node-version}}
          cache: "pnpm"
      - name: Execute all tests
        run: pnpm run test